<a href="https://colab.research.google.com/github/Luke0071990/data-science_bootcamp/blob/main/01_wprowadzanie_01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Spis tresci

Podstawy



In [2]:
import numpy as np
np.__version__

'1.22.4'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

In [6]:
x = np.array([1,3])
x

array([1, 3])

In [7]:
print(x)

[1 3]


In [8]:
type(x)

numpy.ndarray

In [9]:
x.ndim

1

In [10]:
x.shape

(2,)

In [11]:
x.size

2

In [12]:
x.dtype

dtype('int64')

In [15]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [16]:
x.dtype

dtype('float64')

In [18]:
x = np.array([[1,2], [-3,1]])
x

array([[ 1,  2],
       [-3,  1]])

In [19]:
x.ndim

2

In [20]:
x.shape

(2, 2)

In [21]:
x = np.array([[1,2,4], [4,2,1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [22]:
x.shape

(2, 3)

In [27]:
x= np.array(
    [[[4,3,1],
      [3,1,2]],

     [[4,1,3],
      [4,2,1]],

     [[3,2,1],
      [4,3,2]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [28]:
x.ndim

3

In [29]:
x.shape

(3, 2, 3)

In [31]:
A = np.array([1,2,3])
A.dtype

dtype('int64')

In [33]:
A = np.array([1.0,2.1,3.5])
A.dtype

dtype('float64')

In [34]:
A = np.array([1,2,3], dtype = 'float')
A.dtype

dtype('float64')

In [35]:
A = np.array([1,2,3], dtype = 'complex')
A.dtype
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [36]:
A = np.array([1.0,2.1,3.5], dtype = 'int')
A.dtype

dtype('int64')

In [37]:
A

array([1, 2, 3])

In [39]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [41]:
A = np.array([24,120,230], dtype = np.int8)
A.dtype

dtype('int8')

In [42]:
A = np.array([24,120,230], dtype = np.uint8)
A.dtype

dtype('uint8')

In [44]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [45]:
np.zeros(shape=(4,10), dtype = 'int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [47]:
np.ones(shape=(5,5), dtype = 'float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [48]:
np.full(shape = (3,3), fill_value=4, dtype='int'
        )

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [50]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [54]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [56]:
np.arange(start=10, stop=100, step = 10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [57]:
np.arange(start=100, stop=10, step = -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [59]:
np.arange(start = 0, stop = 1 , step = 0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [61]:
np.linspace(start = 0, stop = 1, num = 13) # tworzy zbiordanych podzielony rowno na 11 (num) w wartosci od 0 do 1

array([0.        , 0.08333333, 0.16666667, 0.25      , 0.33333333,
       0.41666667, 0.5       , 0.58333333, 0.66666667, 0.75      ,
       0.83333333, 0.91666667, 1.        ])

In [62]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [63]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [64]:
A.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [65]:
A.reshape((-1,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [66]:
A = np.array([3,1,4,2])
B = np.array([3,-1,3,2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [67]:
A + B

array([6, 0, 7, 4])

In [68]:
A - B

array([0, 2, 1, 0])

In [69]:
A*B


array([ 9, -1, 12,  4])

In [70]:
A/B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [71]:
A +3

array([6, 4, 7, 5])

In [72]:
2*A

array([6, 2, 8, 4])

In [73]:
A + 3*B

array([12, -2, 13,  8])

In [74]:
np.add(A,B)

array([6, 0, 7, 4])

In [75]:
np.subtract(A,B)

array([0, 2, 1, 0])

In [76]:
np.multiply(A,B)

array([ 9, -1, 12,  4])

In [77]:
np.divide(A,B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [81]:
X = np.array([[1,3], [2,0]])
Y = np.array([[6,0], [-1,2]])
print(X, '\n')
print(Y)

[[1 3]
 [2 0]] 

[[ 6  0]
 [-1  2]]


In [79]:
X * Y

array([[ 6,  0],
       [-2,  0]])

In [82]:
np.dot(X,Y)

array([[ 3,  6],
       [12,  0]])

In [83]:
X.dot(Y)

array([[ 3,  6],
       [12,  0]])

In [84]:
Y.dot(X)

array([[ 6, 18],
       [ 3, -3]])

In [85]:
X @ Y

array([[ 3,  6],
       [12,  0]])

In [86]:
np.random.seed(0)

In [87]:
np.random.randn()

1.764052345967664

In [88]:
np.random.randn(10
)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [89]:
np.random.randn(10,4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [91]:
np.random.rand()

0.3687251706609641

In [92]:
np.random.rand(10)

array([0.82099323, 0.09710128, 0.83794491, 0.09609841, 0.97645947,
       0.4686512 , 0.97676109, 0.60484552, 0.73926358, 0.03918779])

In [93]:
np.random.rand(10,2)

array([[0.28280696, 0.12019656],
       [0.2961402 , 0.11872772],
       [0.31798318, 0.41426299],
       [0.0641475 , 0.69247212],
       [0.56660145, 0.26538949],
       [0.52324805, 0.09394051],
       [0.5759465 , 0.9292962 ],
       [0.31856895, 0.66741038],
       [0.13179786, 0.7163272 ],
       [0.28940609, 0.18319136]])

In [95]:
np.random.randint(10) # losowo dodstani liczba niewieksza niz tutaj 10

8

In [97]:
np.random.randint(low = 10, high = 101, size = 50 )

array([87, 40, 34, 12, 13, 23, 50, 82, 29, 82, 36, 76, 62, 77, 71, 24, 14,
       77, 21, 96, 87, 85, 66, 26, 34, 39, 31, 35, 90, 70, 71, 93, 43, 42,
       80, 95, 41, 23, 81, 66, 34, 89, 51, 28, 50, 64, 89, 21, 48, 11])

In [98]:
np.random.choice([4,2,1,3])

3

In [99]:
np.random.choice(['python', 'java', 'sql'])

'sql'

In [101]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
np.random.shuffle(data) # zmiana zachodzi od razu na obiekcie nie trzeba go przypisywać w przeciwieństwie do biblioteki pandas
data

array([1, 4, 6, 9, 8, 5, 0, 3, 7, 2])

In [105]:
np.exp(1)

2.718281828459045

In [106]:
np.sqrt(9)

3.0

In [107]:
np.all([2,3,1])

True

In [108]:
np.all([2,3,0])

False

In [109]:
np.any([1,2,1])

True

In [110]:
np.any([0,0,0])

False

In [111]:
np.any([0,0,1]) # mozemy spradzic czy w jakiejs tablicy ktora ma wiele zer czy posiada jedynke

True

In [112]:
bool(0)

False

In [114]:
bool(1.3)

True

In [116]:
A = np.random.rand(5)
A

array([0.16684751, 0.77905102, 0.8649333 , 0.41139672, 0.13997259])

In [118]:
np.argmax(A)

2

In [119]:
A[np.argmax(A)]

0.8649332956024927

In [121]:
np.argmin(A)

4

In [122]:
A[np.argmin(A)]

0.13997258549320168

In [123]:
np.argsort(A) # przydatna przy klasyfikacji wieloklasowej, pozwala sortowac elementy podajac indeks

array([4, 0, 3, 1, 2])

In [124]:
np.max(A)

0.8649332956024927

In [125]:
np.min(A)

0.13997258549320168

In [126]:
np.mean(A)

0.47244022750173686

In [127]:
np.median(A)

0.41139672375545455

In [128]:
np.std(A)

0.30189698103924306

In [129]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
#A[idx], A[start:stop], A[:stop], A[start:]

In [130]:
A[2]

2

In [131]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [132]:
A[:2]

array([0, 1])

In [134]:
A[[0,2]]

array([0, 2])

In [135]:
A[-1]

19

In [136]:
A[10:15]

array([10, 11, 12, 13, 14])

In [137]:
A =A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [138]:
A[0]

array([0, 1, 2, 3, 4])

In [139]:
A[:,0] #kolumny

array([ 0,  5, 10, 15])

In [140]:
A[:, -1]

array([ 4,  9, 14, 19])

In [141]:
A[1,1]

6

In [142]:
A[1,3]

8

In [147]:
A[1:3, 1:5] # czyli 1 i 2 wiersz oraz od 1 do 4 kolumny

array([[ 6,  7,  8,  9],
       [11, 12, 13, 14]])

In [149]:
A[1,2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [150]:
A


array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [152]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [153]:
for row in A:
  print(row[0])

0
5
10
15


In [154]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [155]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


In [156]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [157]:
A.shape

(4, 5)

In [158]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [160]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [161]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [168]:
A = np.arange(start = -10, stop = 10, step = 0.5)
A.shape
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [169]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [170]:
A[A > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [174]:
np.bitwise_and(A > - 5, A < 5) # mozemy podac kilka warunków / and nie zadziała

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [175]:
A[np.bitwise_and(A > - 5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [176]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [177]:
A[np.bitwise_or(A < -5, A > 5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
         9.5])