<a href="https://colab.research.google.com/github/Luke0071990/data-science_bootcamp/blob/main/01_wprowadzanie/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [6]:
v1 = np.array([-1,4])
v1

array([-1,  4])

In [7]:
np.linalg.norm(v1)

4.123105625617661

In [8]:
v2 = np.array([-10,10,13])
np.linalg.norm(v2)

# mamy dlugosc wektora w przestrzenic R3

19.209372712298546

In [9]:
p = np.array([3,0])
q = np.array([0,4])

np.linalg.norm(p-q)

5.0

In [10]:
p = np.array([3,0,1])
q = np.array([0,4,2])

np.linalg.norm(p-q)

5.0990195135927845

In [12]:
X = np.array([[5,3], [3,9]])
Y = np.array([[1], [-1]])
print(X, '\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [14]:
Z = np.dot(X,Y)
Z


array([[ 2],
       [-6]])

In [15]:
Z.shape

(2, 1)

In [16]:
X = np.array([[2,-1,3],
              [3,1,0]])

Y = np.array([[2,1,-1],
              [0,-1,2],
              [3,2,0]])
print(X, '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [17]:
Z = np.dot(X,Y)
Z

array([[13,  9, -4],
       [ 6,  2, -1]])

In [18]:
Z.shape

(2, 3)

In [20]:
A = np.array([[2,4], [-1,3]])
round(np.linalg.det(A))

10

In [21]:
#Ślad macierzy

A = np.array([[2,4], [-1,3]])
np.trace(A)

5

In [23]:
np.eye(5, dtype = 'int')



array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [24]:
A

array([[ 2,  4],
       [-1,  3]])

In [29]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [27]:
np.set_printoptions(precision = 4, suppress = True)
np.dot(A,B)

array([[1., 0.],
       [0., 1.]])

In [28]:
np.dot(B,A)

array([[ 1., -0.],
       [ 0.,  1.]])

In [30]:
A

array([[ 2,  4],
       [-1,  3]])

In [31]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [32]:
A.T

array([[ 2, -1],
       [ 4,  3]])

In [34]:
A = np.array([[2,4], [1,-1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [35]:
B = np.array([[10], [-1]])

In [38]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.1667,  0.6667],
       [ 0.1667, -0.3333]])

In [40]:
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])

In [41]:
X.shape

(2, 1)